#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__
//For easy changes to game
#define DISPLAY_TIME_SPLASH_SCENE 3
#define TRANSITION_TIME 0.5
#define PIPE_SPAWN_FREQUENCY 0.006
#define PIPE_GAP 4
#define UPPER_SCREEN_PIPE_THRESHOLD 0.65
#define LOWER_SCREEN_PIPE_THRESHOLD 0.35
//lower number means faster
#define PIPE_MOVEMENT_SPEED 0.008
#define BIRD_COLLISION_BITMASK 0x000001
#define OBSTACLE_COLLISION_BITMASK 0X000002
#define POINT_COLLISION_BITMASK 0X000003
//larger numbers means faster
#define BIRD_FALLING_SPEED 0.0085
#define BIRD_FLYING_SPEED 0.3
//larger numbers mean more air time
#define BIRD_FLY_DURATION 0.15
#define	SCORE_FONT_SIZE 0.1

#define BKG_COLLISION_BITMASK 0X000005
//Lower values more frequent
#define MIGHTS_SPAWN_FREQUENCY 0.005
#define MIGHTS_GAP 2
#define UPPER_SCREEN_MIGHTS_THRESHOLD 0.65
#define LOWER_SCREEN_MIGHTS_THRESHOLD 0.35
//lower value faster
#define UMIGHTS_MOVEMENT_SPEED 0.03
#define LMIGHTS_MOVEMENT_SPEED 0.02

//Lower values more frequent
#define ROCKS_SPAWN_FREQUENCY 0.0006
#define ROCKS_GAP 15.5
#define UPPER_SCREEN_ROCKS_THRESHOLD 0.90
#define LOWER_SCREEN_ROCKS_THRESHOLD 0.90
#define ROCKS_COLLISION_BITMASK 0X000004
//lower value faster
#define ROCKS_MOVEMENT_SPEED 0.005

#define EDGE_COLLISION_BITMASK 0X000000

#endif // __DEFINITIONS_H__
