#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__
//For easy changes to game
#define DISPLAY_TIME_SPLASH_SCENE 3
#define TRANSITION_TIME 0.5
#define PIPE_SPAWN_FREQUENCY 0.005
#define PIPE_GAP 5
#define UPPER_SCREEN_PIPE_THRESHOLD 0.65
#define LOWER_SCREEN_PIPE_THRESHOLD 0.35
//lower number means faster
#define PIPE_MOVEMENT_SPEED 0.009
#define BIRD_COLLISION_BITMASK 0x000001
#define OBSTACLE_COLLISION_BITMASK 0X000002
#define POINT_COLLISION_BITMASK 0X000003
//larger numbers means faster
#define BIRD_FALLING_SPEED 0.0065
#define BIRD_FLYING_SPEED 0.1
//larger numbers mean more air time
#define BIRD_FLY_DURATION 0.1
#define	SCORE_FONT_SIZE 0.1

#define BKG_COLLISION_BITMASK 0X000000
//Lower values more frequent
#define MIGHTS_SPAWN_FREQUENCY 0.005
#define MIGHTS_GAP 5
#define UPPER_SCREEN_MIGHTS_THRESHOLD 0.65
#define LOWER_SCREEN_MIGHTS_THRESHOLD 0.35
//lower value faster
#define MIGHTS_MOVEMENT_SPEED 0.03

#endif // __DEFINITIONS_H__
